config/routes.rb
Rails.application.routes.draw do
  root 'test#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/wound", to: "wound#index"
  post "/wound/create_wound", to: "wound#create_wound"
  get "/wound/show_examination", to: "wound#show_examination"
  get "/wound/create_examination", to: "wound#create_examination"
  get "/wound/show_wounddoc_tab", to: "wound#show_wounddoc_tab"
  get "/wound/show_create_documentation", to: "wound#show_create_documentation"
  post "/wound/create_documentation", to: "wound#create_documentation"
  get "/wound/show_documentation", to: "wound#show_documentation"
  patch "/wound/update_documentaion", to: "wound#update_documentation"
  patch "/wound/update_examination", to: "wound#update_examination"
  post "/reminders/update_reminder", to: "reminders#update_reminder"
  get "/reminders/get_reminders",to: "reminders#get_reminders"
  get "/reminders/get_all_reminders_from_patient",to: "reminders#get_all_reminders_from_patient"
  get "/reminders/get_all_reminders",to: "reminders#get_all_reminders"
end

app/models/wound.rb
class Wound < ApplicationRecord
    belongs_to :patient
    has_many :documentations
    has_one :localization
    has_many :pictures 
    has_many :factors_wounds
    has_many :factors, through: :factors_wounds 
    mount_uploaders :images, ImageUploader
    serialize :images , JSON
    has_rich_text :comment
    belongs_to :wound_type
    accepts_nested_attributes_for :factors_wounds
end

app/models/wound_type.rb
class WoundType < ApplicationRecord
    has_many :wounds
end

app/controllers/wound_controller.rb
class WoundController < ApplicationController
    def index 
        #checks if there are ids for a patient and a employee in the url-params and saves it in variable and in a session
        if params[:Patient][:id] != "" 
            @patient = Patient.find(params[:Patient][:id])   
            session[:patient_id] = @patient.id         #session should be almost everywhere accessible 
        end 
        if params[:Employee][:id] != ""
            @employee = Employee.find(params[:Employee][:id])
            session[:employee_id] = @employee.id
        end
    end

    def new_wound
        #here we create a new woundobject
        @wound = Wound.new
    end 

    def create_wound 
        #here we use respond to to debug and see which params are passed to the controller-action
        respond_to do |f|
           f.js
           f.html{render plain: params}
        end
        #the wound object get the params from the form 
        @wound = Wound.new(wound_params)
        
        if @wound.save 
            #Manually saves the wound_id and the factor_id into the FactorsWound table by iterrating the params of the form
            #here we get the values of the params for example woundfactors =>{factors =>["",1,2], 2=> text that you have written into the input}
            params[:woundfactors][:factors][1..-1].each do |x|        
                FactorsWound.create({factor_id: x , wound_id: @wound.id,value: params[:woundfactors][x]})
            
            end



            update_cave()
            #creates a database entry in the Localization-table with the information of the params
            Localization.create({wound_id: @wound.id,body_part: params[:Localization], wound_since: params[:localization][:wound_since],recidivism: params[:localization][:recidivism]})
        end 
    end 
    def create_examination
        #this will be called if you click on "Neue Wunde anlegen because the form needs a woundobject"
        @wound = Wound.new

    end 
    def show_examination 
        #if clicked on a "Wunfaufnahme-tab" , we need the woundobject that is represented there
        @wound= Wound.find(params[:wound]) #we need the specific wound_id from the params
        respond_to do |f|
            f.html{render plain: params}
            f.js
        end
    end 
    def show_wounddoc_tab
        @wound = Wound.find(params[:wound])
    end
    def update_examination
         #here we use respond to to debug and see which params are passed to the controller-action
        respond_to do |f|
            f.js
            f.html{render plain: params}
         end
        @wound = Wound.find(params[:wound_id])  
        #that if is needed here, if you delete the last picture, after that the whole column or all pictures get deleted 
        #carrierwave has problems when you dont have pictures after deleting the last ones
        if params[:wound][:images].nil?
            @wound.remove_images!
            @wound.save!
        end 
        #normal update of a wound with new params 
        @wound.update(wound_params)

        #Manually saves the wound_id and the factor_id into the FactorsWound table by iterrating the params of the form
        #here we get the values of the params for example woundfactors =>{factors =>["",1,2], 2=> text that you have written into the input}
        @wound.factors_wounds.delete_all
        params[:woundfactors][:factors][1..-1].each do |x|          
            FactorsWound.create({factor_id: x , wound_id: @wound.id,value: params[:woundfactors][x]})
             
        end
        update_cave
        #updates the localizationentry, that is already createds
        Localization.find_by(wound_id: @wound.id).try(:update,{body_part: params[:Localization],wound_since: params[:localization][:wound_since],recidivism: params[:localization][:recidivism]})
    end 
    
    #is called if you clicked on "Neues Datum"
    def show_create_documentation
        respond_to do |f|
            f.js
            f.html{render plain: params}
         end 
         #new documentationobject created
        @documentation = Documentation.new
        #finds the wound that will get the newly created documentation
        @wound = Wound.find(params[:wound])

        #this line searches the last documentation from the wound.This is needed for a prefilled documentation
        @doc_last = @wound&.documentations.try(:last)
       
    end
    
    def batchdoc(boolean)
        #in update documentation the old batchdocs must be deleted , so there wont be duplicates
        if boolean
            BatchDocumentation.where(documentation_id: @documentation.id).delete_all
        end 
        # checks if the param batchdoc even exists
        if  params[:batchdoc] != nil
            @medproducts = params[:batchdoc][:medproducts] 
            @batchnrs = params[:batchdoc][:batchnrs]
            # zip combines two arrays so we have two string arrays ,one for medproducts and one for batchnrs example [["Gel","56165"],["Tuch","2121651"]]
            @medproducts.zip(@batchnrs).each do |medproduct,batchnr|
                #empty batchdocs wont be saved
                if medproduct != "" || batchnr != ""
                    BatchDocumentation.create(medical_product: medproduct , batch_number: batchnr , documentation_id: @documentation.id)
                end 
            end
        end
    end
    def create_documentation
        #here we need to save the documentation first , so that we have an id for the verification
        @documentation = Documentation.new(wound_id: params[:documentation][:wound_id])
        #we save the documentation here immediately because its important for the verifications
        @documentation.save
        #@documentation = Documentation.new(documentation_params) 
        @wound = Wound.find(params[:documentation][:wound_id]) 
        verification(true)
        #woundphases are saved in a extra-table between documentation and woundphase_Options, so every checkbox needs to be created manually
        params[:woundphases][:wound_phase_options].reject{|x| x==""}.each do |x|       
            PhaseOption.create({wound_phase_option_id: x , documentation_id: @documentation.id})
        end
        #the extra table between infections and documentation is something special. It has its own model because it has an extra column for values, it can save the disabled input fields form the checkboxes
        params[:infections][:infections_ids].reject{|x| x==""}.each do |x|       
            DocumentationsInfection.create({infection_id: x , documentation_id: @documentation.id, value: params[:infections][x]})
        end
        #same as woundphases
        params[:documentation][:skin_care_ids].reject{|x| x==""}.each do |x|       
             DocumentationsSkinCare.create({skin_care_id: x , documentation_id: @documentation.id})
        end

        batchdoc(false)
        Localization.find_by(wound_id: @wound.id).try(:update,{body_part: params[:Localization]})
        #the documentation must be updated after the creation if verifications, because the verification methdd compares old values with new values
        @documentation.update(documentation_params)
        #the comments are saved manually and the ActionTextRichText-Model is created by us, so we can save comments on our own
        params[:comments]&.each do |c| 
            ActionTextRichText.create(name: "bemerkung", body: c , record_type: "Documentation", record_id: @documentation.id)
        end
        #params[:reminders] contains an array that is built like this [text,time], so we need to iterrate every two items of the array 
        params[:reminders]&.each_slice(2) do |r,z|  
            Reminder.create(text: r, publication_date: z , documentation_id: @documentation.id , patient_id: session[:patient_id])
        end


        


    end
    def show_documentation
        @documentation = Documentation.find(params[:documentation])
    end 
    def update_documentation
        #get all params if the show_view_form
        @documentation = Documentation.find(params[:documentation][:id])
        @wound = @documentation.wound_id
        verification(false)
        #same principle as in the wound
        if params[:documentation][:images].nil?
            @documentation.remove_images!
            @documentation.save!
        end 
        #the documentation must be updated after the verification_method, so the verification method still has access to the old values of te documentation
        @documentation.update(documentation_params)
        batchdoc(true)
        #instead of searching each id and updating each record , we drop all checkboxes of the documentation and create each one again
        @documentation.documentations_infections.delete_all
        params[:infections][:infections_ids].reject{|x| x==""}.each do |x|       
            DocumentationsInfection.create({infection_id: x , documentation_id: @documentation.id, value: params[:infections][x]})
        end
         #instead of searching each id and updating each record , we drop all checkboxes of the documentation and create each one again
        @documentation.documentations_skin_cares.delete_all
        params[:documentation][:skin_care_ids].reject{|x| x==""}.each do |x|       
            DocumentationsSkinCare.create({skin_care_id: x , documentation_id: @documentation.id})
        end
         #instead of searching each id and updating each record , we drop all checkboxes of the documentation and create each one again
        @documentation.phase_options.delete_all
        params[:woundphases][:wound_phase_options].reject{|x| x==""}.each do |x|       
            PhaseOption.create({wound_phase_option_id: x , documentation_id: @documentation.id})
        end
        Localization.find_by(wound_id: @wound).try(:update,{body_part: params[:Localization]})
        #same as in the create_documentation
        params[:comments]&.each do |c| 

app/helpers/wound_helper.rb
module WoundHelper
end

app/views/wound/_all_images.html.erb
<button id="show_all_images" type="button" class="btn btn-outline-info">Alle Bilder dieser Wunde</button>
<!-- Trigger the Modal -->
<!-- The Modal -->
<div id="show_all_images_modal" class="modal">

  <!-- The Close Button -->
  <span id="close_all_images"class="close">&times;</span>

  <!-- Modal Content (The Image) -->
  <div class="modal-content" id="modal-all-images">
 <div id="all_images_carousel" class="carousel slide" data-interval="false"data-ride="carousel">
 <%bigarray = Wound.find(w_id).images.concat(Wound.find(w_id).documentations.map{|x| x.images}.flatten) %>
 
  <ol id="carousel-indicators-all-images" class="carousel-indicators"> 
    <%bigarray.each_with_index do |a,index|%>
    <%if index == 0%>
        <li class="active" data-target="#all_images_carousel" data-slide-to=<%=index%>><img class="new-thumb" src=<%="#{a.url}"%>></li>
        
    <%else%>
       <li data-target="#all_images_carousel" data-slide-to=<%=index%>><img class="new-thumb" src=<%="#{a.url}"%>></li>
    <%end%>  
    <%end%>
  </ol>
            <div id="carousel-inner-all-images"class="carousel-inner">
                
                <%bigarray.each_with_index do |a,index|%>
                    <%if index == 0%>
                        <div class="carousel-item active">
                            <img class="d-block w-100" src=<%="#{a.url}"%> %>>
                            <div class="carousel-caption d-none d-md-block"><%= a.url.split("/")[5]%></div>
                        </div>     
                    <%else%>
                        <div class="carousel-item">
                            <img class="d-block w-100" src=<%="#{a.url}"%> %>>
                            <div class="carousel-caption d-none d-md-block"><%= a.url.split("/")[5]%></div>
                        </div>
                    <%end%>
                <%end%>
               
            </div>
  
  
  
  
  
  <a class="carousel-control-prev" href="#all_images_carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#all_images_carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  </div>
    
</div>

app/views/wound/_cave.html.erb
    <div class="card">
        <div class="card-header" id="cave">
            <h6 class="mb-0">
               Cave  
            </h6>
        </div>

         <div class="card-body">
          <div class="row row-cols-xl-3">
    <div class ="form-group-cave">
        <label for="allergy"> Allergien:</label>
        <%= text_area(:cave, :allergy, value: Cave.find_by(patient_id: session[:patient_id].to_s).try(:allergy)) %>    
</div>

    <div class ="form-group-cave">
        <label for= "germs"> Resistente Keime:</label>
        <%= text_area(:cave, :resistant_germs, value: Cave.find_by(patient_id: session[:patient_id].to_s).try(:resistant_germs)) %> 
    </div>

    <div class ="form-group-cave">
        <label for= "other"> Sonstiges:</label>
        <%= text_area(:cave, :other, value: Cave.find_by(patient_id: session[:patient_id].to_s).try(:other)) %>
    </div>
</div>
  </div>
</div>

app/views/wound/_comment.html.erb
<div class="form-group">
    <%= rich_text_area "wound", "comment"%>
</div>

app/views/wound/_comment_history.html.erb
    <div class="card">
        <div class="card-header" id="comment">
            <div class="row">
                <div class="col-sm-5 col-lg-7" >
                <span style="font-size:10pt">+</span>
                     <button type="button" class="btn button-transparent btn-sm" data-toggle="collapse"
                            data-target="#comment-content" aria-expanded="true"
                            aria-controls="comment-content">
                            Verlauf Bemerkungen
                            </button>
                </div>
            <div class="col-sm-7 col-lg-5 ">
                <button data-dialog-target="#dialog" id="new-comment" type="button" class="btn btn-info mx-2 my-2" >Neue Bemerkung</button>
                <div class="dialog" id="dialog">
                    <div class="dialog-header">
                        <div class="title">Neue Bemerkung erstellen</div>
                            <button id="comment-close-button" type="button" class="close-button">&times;</button>
                    </div>
                    <div class="dialog-body">
                            <%= render partial: "/wound/comment_doc" %>
                            <%= render partial: "/wound/comment_template" %>
                            <button id="save-comment" type="button" class="btn btn-success">Hinzufügen</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="comment-content" class="collapse" aria-labelledby="comment">
        <div class="card-body">
            <div id="comment-content"></div>
            <div id="scroller-verlauf">
                <table id="commentlist">
                    <tr>
                        <th id="bemerkung">Bemerkung</th>
                        <th id="bemerkung">Datum</th>
                    </tr>
                    <tr style="background-color: white; border:solid lightgray 0.5px;">
                        <td id="bemerkung">
                                <% ActionTextRichText.where(record_type: "Wound", record_id:
                            w_id)&.each do |b| %>
                            <span style="font-weight: bolder">Wundaufnahme:</span>
                            <%== b.body%>
                        </td>
                        <td>
                            <%=b.created_at.strftime("%d.%m.%Y")%>
                            <%end%>
                        </td>
                    </tr>
                    <%documentation_ids=Wound.find(w_id).documentations.where("id<=?",@documentation.id.nil? ?Documentation.last.try(:id) : @documentation.id).pluck(:id)%>
                    <% documentation_ids.delete(@documentation.id)%>

                    <%documentation_ids&.each do |c|%>
                    <%ActionTextRichText.where(record_type:"Documentation",record_id: c)&.each do |rt|%>
                    <tr style="background-color: white; border:solid lightgray 0.5px;">
                        <td id="bemerkung">
                                <span style="font-weight: bolder">Bisherige Bemerkungen:</span>
                                
                                <%==  rt.body %>
                        </td>
                        <td>

                            <%=rt.created_at.strftime("%d.%m.%Y")%>    
                        </td>
                        
                    </tr>
                    <%end%>
                    <%end%>
                    
                    <% ActionTextRichText.where(record_type: "Documentation", record_id:@documentation.id)&.each do |a| %>
                    <tr>
                        <td id="bemerkung">
                            <%== a.body %>
                        </td>
                        <td>
                            <%=a.created_at.strftime("%d.%m.%Y")%>
                        </td>
                        <% end %>
                    </tr>
                </table>
            </div>
        </div>
    </div>
                                    
                                

app/views/wound/_comment_template.html.erb
<div class="template" id="template">
    <div class="template-header">
        <div class="template-title">Vorlage wählen</div>
        <button id="template-close-button" type="button" class="close-button-template">&times;</button>
    </div>
    <div class="scroller">
    <div class="template-body">
         <% Vorlage.all.each do |a|%>
            <div class="auswahl">
            <div id="hover_name">
            <%=a.template_name %>
            <div id="hover_content">
            <%=a.template_content%>
            </div>
            </div>
            
            </div>
            <%end%>
        </div>
        </div>
        <div class="template-footer">
        <button id="save-template" type="button" class="btn btn-success">Wahl bestätigen</button>
    </div>
</div>

app/views/wound/_images.html.erb
<div id="carouselExampleControls" class="carousel slide" data-interval="false" data-ride="carousel">
    <div class="carousel-inner">      
    <%=wd.images.length%>
    <div class="carousel-item active">
    <span id="carousel-images">
        <%wd.images.each_with_index do |a,index|%>
                <%= hidden_field_tag("#{wd.class.to_s.underscore}[images][]",a.identifier)%>
                <%= image_tag "#{a.url}",class:"popup_link thumbnail"%>
                <%if(index.send("+",1)%4== 0)  && (index.send("+",1) < wd.images.length)%>
                    <%== "</span></div><div class='carousel-item'><span id='carousel-images'>"%>
                <%end%>
        <%end%>
    </span>
    </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon"  aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>



    <div class="modal" id="myModal">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                        <button id="modaldismiss" type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div id="modalbody" class="modal-body">
                    Modal body..
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button hidden id="modalundelete" type="button" class="btn btn-success" data-dismiss="modal">Wiederherstellen</button>
                    <button hidden id="modaldelete" type="button" class="btn btn-danger" data-dismiss="modal">Löschen</button>
                    <button id="modalclose" type="button" class="btn btn-primary" data-dismiss="modal">Schließen</button>
                </div>
            </div>
        </div>
    </div>  

app/views/wound/create_examination.js.erb
document.getElementById("wound-content").innerHTML="<%= j (render partial: "/wound/wound_examination")%>"
$(".selectpicker").selectpicker()

app/views/wound/create_wound.js.erb
document.getElementById("wound-tabs").innerHTML="<%= j (render partial: '/wound/wound_tabs')%>"
$("#myTabMD a").get(-2).click();

app/views/wound/index.html.erb
<%="Patient: " + @patient.info + "  ||  "%>
<%="Mitarbeiter: " + @employee.info%></br>
<%= render partial: "reminders/reminder_popup"%>
<span id="wound-tabs">
    <%= render partial: "/wound/wound_tabs"%>
</span>

app/views/wound/show_documentation.js.erb
document.getElementById("wounddoc-content").innerHTML="<%=j (render partial: '/wound/show_documentation')%>"
$("path[value=\"" + $("#Localization").val() + "\"]").addClass("path-cl-selected")
$("#infections_1").prop("disabled", !($("#infections_infections_ids_1").prop("checked")))
$("input[type='file']").prop("disabled", !($("#documentation_permission").prop("checked")))
$(".selectpicker").selectpicker()
$("#Wundexsudation,#Wundinfektion,#Wundränder,#Wundumgebung,#Debridement,#Wundspülung,#Hautzustand,#Hautpflege,span[id='Wundauflage']").each(function(){
   $(this).children().children().get(0).click()
   $(this).children().children().get(0).click()
})
$("#Exsudationsphase,#Granulationsphase,#Epithelisierungsphase,#Nekrotisch").each(function(){
    $(this).children().children().get(0).click()
    $(this).children().children().get(0).click()
})
$("#myRange").change()
$("#width").change()
$("#batchlist").change()

//,#EinverständnisvomPatient,#WundvisitemitArzt"

app/views/wound/show_examination.js.erb
document.getElementById("wounddoc-content").innerHTML="<%=j (render partial: "/wound/show_examination")%>"
$("#wundheilung-faktoren button").trigger("click")
$("path[value=\"" + $("#Localization").val() + "\"]").addClass("path-cl-selected")
$("#woundfactors_13").prop("disabled", !($("#woundfactors_factors_13").prop("checked")))
$("input[type='file']").prop("disabled", !($("#wound_permission").prop("checked")))
$(".selectpicker").selectpicker()

app/views/wound/show_wounddoc_tab.js.erb
document.getElementById("wound-content").innerHTML="<%=j (render partial: "/wound/wounddoc_tab")%>"
$("#myDocMD a").first()[0].click();

app/views/wound/update_examination.js.erb
document.getElementById("wounddoc-content").innerHTML="<%=j (render partial: "/wound/show_examination")%>"
$("path[value=\"" + $("#Localization").val() + "\"]").addClass("path-cl-selected")
$("#woundfactors_13").prop("disabled", !($("#woundfactors_factors_13").prop("checked")))
$("input[type='file']").prop("disabled", !($("#wound_permission").prop("checked")))
$(".selectpicker").selectpicker()